sudo: required

language: node_js
node_js:
  - "0.10"

env:
  COMPOSE_VERSION: 1.4.2

services:
  - docker

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose-bin
 - chmod +x docker-compose-bin
 - sudo mv docker-compose-bin /usr/local/bin/docker-compose
 - sudo service docker restart ; sleep 10

script:
- npm run test

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
  email: false