api:
   build: .
   command: nodemon --watch api --watch database api/api.js
   net: host
   environment:
      - VIRTUAL_HOST=pheromon.ants.builders
      - VIRTUAL_PORT=4000
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elements
      - PGPASSWORD=elements
      - UPDATER_RANGE_START=2200
      - UPDATER_RANGE_SIZE=10
      - NODE_ENV=test
   volumes:
      - ./:/pheromon
   log_driver: "none" 
broker:
   build: .
   command: nodemon --watch broker broker/index.js
   links:
      - dbtest:db
      - redis
   ports:
      - "1883:1883"
      - "5100:5100"
   environment:
      - VIRTUAL_PORT=5100
      - NODE_ENV=test
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./:/pheromon
   log_driver: "none" 
dbtest:
   image: postgres:9.4
   ports:
      - "5432:5432"
   environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - PGPASSWORD=elements # don't change the name of the variable for pg_dump
      - POSTGRES_PASSWORD=elements
   log_driver: "none" 
redis:
   image: redis:3
   log_driver: "none" 
tests:
   build: .
   command: node ./tests/index.js
   dockerfile: Dockerfile-test
   net: host
   environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - PGPASSWORD=elements # don't change the name of the variable for pg_dump
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./:/pheromon/
   tty: true
