api:
   build: ./
   command: nodemon api/api.js
   links:
      - db
      - broker
   ports:
      - "4000:4000"
   environment:
      - VIRTUAL_PORT=4000
      - INTERNAL_PORT=55555
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elements
      - PGPASSWORD=elements
      - NODE_ENV=development
   volumes:
      - ./:/pheromon
broker:
   build: .
   command: nodemon broker/endpoint.js
   links:
      - db
   ports:
      - "5100:5100"
   environment:
      - VIRTUAL_PORT=5100
      - INTERNAL_PORT=55555
      - NODE_ENV=development
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./:/pheromon
db:
   image: postgres:9.4
   environment:
      - POSTGRES_PASSWORD=elements
