pheromon:
   build: .
   command: node tools/init-db2
   links:
      - dbtest:db
   environment:
      - POSTGRES_USER=postgres
      - PGPASSWORD=elements
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./:/pheromon/
   tty: true

dbtest:
   image: postgres:9.4
   environment:
      - POSTGRES_USER=postgres
      - PGPASSWORD=elements # don't change the name of the variable for pg_dump
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./data:/var/lib/postgresql
   tty: true
