dashboard:
   build: .
   command: nodemon server/dashboard.js
   links:
      - db
      - endpoint
   ports:
      - "4000:4000"
   environment:
      - VIRTUAL_HOST=6element.ants.builders 
      - VIRTUAL_PORT=4000
      - INTERNAL_PORT=55555
      - POSTGRES_PASSWORD=elements
      - NODE_ENV=production
   volumes:
      - ./:/pheromon/
      - /data/6element:/pheromon/data
   restart: always
endpoint:
   build: .
   command: nodemon server/endpoint.js
   links:
      - db
   ports:
      - "5100:5100"
   environment:
      - VIRTUAL_PORT=5100
      - INTERNAL_PORT=55555
      - NODE_ENV=production
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./:/pheromon/
   restart: always
admin:
   build: .
   command: nodemon server/admin.js
   links:
      - db
      - endpoint
   ports:
      - "4001:4001"
   environment:
      - VIRTUAL_HOST=sensors.ants.builders 
      - VIRTUAL_PORT=4001
      - INTERNAL_PORT=55555
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elements
      - PGPASSWORD=elements
      - NODE_ENV=production
   volumes:
      - ./:/pheromon/
   restart: always
db:
   image: postgres:9.4
   environment:
      - NODE_ENV=production
      - POSTGRES_PASSWORD=elements
   restart: always