api:
   build: ./
   command: nodemon --watch api --watch database api/api.js
   links:
      - dbdev:db
      - broker
   ports:
      - "3900:3900"
   environment:
      - VIRTUAL_HOST=pheromon.ants.builders
      - VIRTUAL_PORT=3900
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elements
      - PGPASSWORD=elements
      - NODE_ENV=development
   volumes:
      - ./:/pheromon
   tty: true
broker:
   build: .
   command: nodemon --watch broker broker/index.js
   links:
      - dbdev:db
      - redis
   ports:
      - "1883:1883"
   environment:
      - VIRTUAL_PORT=1883
      - NODE_ENV=development
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./:/pheromon
   tty: true
dbdev:
   image: postgres:9.4
   environment:
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./data:/var/lib/postgresql
   tty: true
redis:
   image: redis:3
   log_driver: "none" 
