api:
   build: ./
   command: nodemon api/api.js
   net: host
   # ports:
   #    - "3900:3900"
   environment:
      - VIRTUAL_HOST=pheromon.ants.builders
      - VIRTUAL_PORT=3900
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elements
      - PGPASSWORD=elements
      - UPDATER_RANGE_START=2200
      - UPDATER_RANGE_SIZE=100
      - NODE_ENV=production
   volumes:
      - ./:/pheromon
      - /home/sensorSSH/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - /home/sensorSSH/.ssh/known_hosts:/root/.ssh/known_hosts
      - /etc/ssh/ssh_config:/etc/ssh/ssh_config:ro
   tty: true
   restart: always
broker:
   build: .
   command: nodemon broker/index.js
   links:
      - db
      - redis
   ports:
      - "1883:1883"
   environment:
      - VIRTUAL_PORT=1883
      - NODE_ENV=production
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./:/pheromon
   tty: true
   restart: always
db:
   image: postgres:9.4
   environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=elements
      - NODE_ENV=production
   ports:
      - "5432:5432"
   volumes:
      - /data/pheromon/db:/var/lib/postgresql/data
   tty: true
   restart: always
redis:
   image: redis:3
   ports:
      - "6379:6379"
   log_driver: "none" 
   restart: always
