dashboard:
   build: .
   command: node server/dashboard.js
   links:
      - db
      - endpoint
   ports:
      - "4000:4000"
   environment:
      - VIRTUAL_PORT=4000
      - INTERNAL_PORT=55555
      - POSTGRES_PASSWORD=elements
      - NODE_ENV=development
   volumes:
      - ./:/pheromon/
endpoint:
   build: .
   command: node server/endpoint.js
   links:
      - db
   ports:
      - "5100:5100"
   environment:
      - VIRTUAL_PORT=5100
      - INTERNAL_PORT=55555
      - NODE_ENV=development
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./:/pheromon/
admin:
   build: .
   command: node server/admin.js
   links:
      - db
      - endpoint
   ports:
      - "4001:4001"
   environment:
      - VIRTUAL_PORT=4001
      - INTERNAL_PORT=55555
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elements
      - PGPASSWORD=elements
      - NODE_ENV=development
   volumes:
      - ./:/pheromon/
db:
   image: postgres:9.4
   environment:
      - POSTGRES_PASSWORD=elements

tests:
  build: ./tests
  links:
   - endpoint
   - admin
   - dashboard
  command: node ./index.js
  volumes:
   - ./tests:/tests/
