pheromon:
   build: .
   command: node tools/init-db
   links:
      - dbdev:db
   environment:
      - POSTGRES_USER=postgres
      - PGPASSWORD=elements
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./:/pheromon/
   tty: true

dbdev:
   image: postgres:9.4
   environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - PGPASSWORD=elements # don't change the name of the variable for pg_dump
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./data:/var/lib/postgresql
   tty: true