api:
   build: ./
   command: nodemon --watch api --watch database api/api.js
   net: host
   # ports:
   #    - "3900:3900"
   environment:
      - VIRTUAL_HOST=pheromon.ants.builders
      - VIRTUAL_PORT=3900
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elements
      - PGPASSWORD=elements
      - UPDATER_RANGE_START=2200
      - UPDATER_RANGE_SIZE=2
      - NODE_ENV=development
   volumes:
      - ./:/pheromon
      - /home/sensorSSH/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - /home/sensorSSH/.ssh/known_hosts:/root/.ssh/known_hosts
      - /etc/ssh/ssh_config:/etc/ssh/ssh_config:ro
   tty: true
broker:
   build: .
   command: nodemon --watch broker broker/index.js
   links:
      - dbdev:db
      - redis
   ports:
      - "1883:1883"
   environment:
      - VIRTUAL_PORT=1883
      - NODE_ENV=development
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./:/pheromon
   tty: true
dbdev:
   image: postgres:9.4
   environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=elements
   ports:
      - "5432:5432"
   volumes:
      - ./data:/var/lib/postgresql
   tty: true
redis:
   image: redis:3
   ports:
      - "6379:6379"
   log_driver: "none" 
