api:
   build: ./
   command: nodemon api/api.js
   links:
      - db
      - broker
   ports:
      - "4000:4000"
   environment:
      - VIRTUAL_PORT=4000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elements
      - PGPASSWORD=elements
      - NODE_ENV=production
   volumes:
      - ./:/pheromon
   tty: true
   restart: always
broker:
   build: .
   command: nodemon broker/index.js
   links:
      - db
   ports:
      - "5100:5100"
   environment:
      - VIRTUAL_PORT=5100
      - NODE_ENV=production
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./:/pheromon
   tty: true
   restart: always
db:
   image: postgres:9.4
   environment:
      - POSTGRES_PASSWORD=elements
      - NODE_ENV=production
   volumes:
      - /data/pheromon:/var/lib/postgresql
   tty: true
   restart: always
