api:
   build: .
   command: nodemon --watch api --watch database api/api.js
   links:
      - dbtest:db
      - broker
   ports:
      - "4000:4000"
   environment:
      - VIRTUAL_PORT=4000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elements
      - PGPASSWORD=elements
      - NODE_ENV=development
   volumes:
      - ./:/pheromon
   log_driver: "none" 
broker:
   build: .
   command: nodemon --watch broker broker/index.js
   links:
      - dbtest:db
   ports:
      - "5100:5100"
   environment:
      - VIRTUAL_PORT=5100
      - NODE_ENV=development
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./:/pheromon
   log_driver: "none" 
dbtest:
   image: postgres:9.4
   environment:
      - POSTGRES_USER=postgres
      - PGPASSWORD=elements # don't change the name of the variable for pg_dump
      - POSTGRES_PASSWORD=elements
   log_driver: "none" 
tests:
   build: .
   dockerfile: Dockerfile-test
   links:
      - api
      - broker
      - dbtest:db
   environment:
      - POSTGRES_USER=postgres
      - PGPASSWORD=elements # don't change the name of the variable for pg_dump
      - POSTGRES_PASSWORD=elements
   command: node ./tests/index.js
   volumes:
      - ./:/pheromon/
   tty: true
